
{{ if hasKey .Values.env }}
  {{ fail "The Value env has been renamed and moved to cortex-os.configEnv. Refer to https://www.cortexos.ai/docs/local/helm_chart#migrate for more information" }}
{{ end }}